version: "2.13.0"

volumes:
  mysqldb:

services:
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
  backend:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    image: mysql
    volumes:
      - mysqldb:/data/db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_ROOT_PASSWORD: root